[project]
name = "inconspiquous"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ruff>=0.6.5",
    "xdsl>=0.22.0",
]

[project.optional-dependencies]
dev = [
  "pyright>=1.1.380",
  "pytest>=8.3.3",
  "lit<16.0.0",
  "filecheck==0.0.23",
  "pre-commit==3.3.1",
]