[project]
name = "inconspiquous"
version = "0.1.0"
description = "A testing ground for quantum computing compilation ideas in xdsl"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "xdsl>=0.22.0",
]

[project.optional-dependencies]
dev = [
  "ruff>=0.6.5",
  "pyright>=1.1.380",
  "pytest>=8.3.3",
  "lit<16.0.0",
  "filecheck==0.0.23",
  "pre-commit==3.3.1",
]

[project.scripts]
quopt = "inconspiquous.tools.inconspiquous_opt_main:main"

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyright]
typeCheckingMode = "strict"
include = ["inconspiquous"]
