# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI - Python-based Testing

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up uv
      uses: yezz123/setup-uv@v4
      with:
        uv-venv: "venv"

    - name: Sync
      run: |
        uv sync --dev

    - name: Test with pytest
      run: |
        pytest -W error

    - name: Execute lit tests
      run: |
        export PYTHONPATH=$(pwd)
        lit -v tests/filecheck/
